{{- if .Values.global.modules.publicDomainTemplate }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cdi-uploadproxy
  namespace: d8-cdi
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: {{ include "helm_lib_module_ingress_class" . | quote }}
  tls:
  - hosts:
    - {{ include "helm_lib_module_public_domain" (list . "cdi-uploadproxy") }}
    secretName: {{ include "helm_lib_module_https_secret_name" (list . "ingress-tls") }}
  rules:
  - host: {{ include "helm_lib_module_public_domain" (list . "cdi-uploadproxy") }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cdi-uploadproxy
            port:
              number: 443
{{- end }}
