apiVersion: v1
kind: Service
metadata:
  name: ipam-webhook
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ipam-webhook")) | nindent 2 }}
spec:
  selector:
    app: ipam-webhook
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
