apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm2
spec:
  running: true
  template:
    metadata:
      annotations:
        cni.cilium.io/ipAddrs: 10.10.10.2
        cni.cilium.io/macAddrs: f6:e1:74:94:b8:1a
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
      #    - disk:
      #        bus: scsi
      #      name: my-pvc
      #      serial: my-pvc
          interfaces:
          - macvtap: {}
            name: default
          #- macvtap: {}
          #  name: red
          #  macAddress: "02:52:32:00:00:00"
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      #- multus:
      #    networkName: whereaboutsexample
      #  name: red
      terminationGracePeriodSeconds: 30
      volumes:
      - containerDisk:
          image: kubevirt/fedora-cloud-container-disk-demo:latest
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
      #- name: my-pvc
      #  persistentVolumeClaim:
      #    claimName: my-cloned-pvc
