apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: operationpolicies.deckhouse.io
  labels:
    heritage: deckhouse
    module: admission-policy-engine
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: operationpolicies
    singular: operationpolicy
    kind: OperationPolicy
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          description: |
            TODO
          properties:
            spec:
              type: object
              required: ["match", "policies"]
              properties:
                policies:
                  type: object
                  properties:
                    allowedRepos:
                      type: array
                      items:
                        type: string
                    requiredLabels:
                      type: array
                      items:
                        type: string
                match:
                  type: object
                  properties:
                    namespaceSelector:
                      oneOf:
                        - required: [matchNames]
                        - required: [excludeNames]
                        - required: [labelSelector]
                      type: object
                      description: Specifies the Namespace selector to filter objects with.
                      properties:
                        matchNames:
                          type: array
                          description: "Include only a particular set of namespaces."
                          items:
                            type: string
                        excludeNames:
                          type: array
                          description: "Include all namespaces except a particular set."
                          items:
                            type: string
                        labelSelector:
                          type: object
                          description: |
                            Specifies the label selector to filter namespaces.

                            You can get more into [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).
                          anyOf:
                            - required: [ matchLabels ]
                            - required: [ matchExpressions ]
                          properties:
                            matchLabels:
                              type: object
                              description: List of labels which a namespace should have.
                              example: { "foo": "bar", "baz": "who" }
                              additionalProperties:
                                type: string
                            matchExpressions:
                              type: array
                              description: List of label expressions for namespaces.
                              example: |
                                ```yaml
                                matchExpressions:
                                - key: tier
                                  operator: In
                                  values:
                                  - production
                                  - staging
                                ```
                              items:
                                type: object
                                required:
                                  - key
                                  - operator
                                properties:
                                  key:
                                    type: string
                                  operator:
                                    type: string
                                    enum:
                                      - In
                                      - NotIn
                                      - Exists
                                      - DoesNotExist
                                  values:
                                    type: array
                                    items:
                                      type: string
                    labelSelector:
                      type: object
                      description: |
                        Specifies the label selector to filter Pods with.

                        You can get more into [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).
                      anyOf:
                        - required:
                            - matchLabels
                        - required:
                            - matchExpressions
                      properties:
                        matchLabels:
                          type: object
                          description: List of labels which Pod should have.
                          example: { "foo": "bar", "baz": "who" }
                          additionalProperties:
                            type: string
                        matchExpressions:
                          type: array
                          description: List of label expressions for Pods.
                          example: |
                            ```yaml
                            matchExpressions:
                            - key: tier
                              operator: In
                              values:
                              - production
                              - staging
                            ```
                          items:
                            type: object
                            required:
                              - key
                              - operator
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                                enum:
                                  - In
                                  - NotIn
                                  - Exists
                                  - DoesNotExist
                              values:
                                type: array
                                items:
                                  type: string


