{{- define "cdi-images" -}}
- name: CONTROLLER_IMAGE
  value: "{{ $.Values.global.modulesImages.registry }}:{{ $.Values.global.modulesImages.tags.cdi.cdiController }}"
- name: IMPORTER_IMAGE
  value: "{{ $.Values.global.modulesImages.registry }}:{{ $.Values.global.modulesImages.tags.cdi.cdiImporter }}"
- name: CLONER_IMAGE
  value: "{{ $.Values.global.modulesImages.registry }}:{{ $.Values.global.modulesImages.tags.cdi.cdiCloner }}"
- name: APISERVER_IMAGE
  value: "{{ $.Values.global.modulesImages.registry }}:{{ $.Values.global.modulesImages.tags.cdi.cdiApiserver }}"
- name: UPLOAD_SERVER_IMAGE
  value: "{{ $.Values.global.modulesImages.registry }}:{{ $.Values.global.modulesImages.tags.cdi.cdiUploadserver }}"
- name: UPLOAD_PROXY_IMAGE
  value: "{{ $.Values.global.modulesImages.registry }}:{{ $.Values.global.modulesImages.tags.cdi.cdiUploadproxy }}"
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cdi-operator
    operator.cdi.kubevirt.io: ""
    prometheus.cdi.kubevirt.io: "true"
  name: cdi-operator
  namespace: d8-cdi
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: cdi-operator
        operator.cdi.kubevirt.io: ""
        prometheus.cdi.kubevirt.io: "true"
    spec:
      containers:
      - env:
        {{- include "cdi-images" . | nindent 8 }}
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: {{ include "cdi-images" . | sha256sum | trunc 7 }}
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        - name: MONITORING_NAMESPACE
        image: "{{ $.Values.global.modulesImages.registry }}:{{ $.Values.global.modulesImages.tags.cdi.cdiOperator }}"
        imagePullPolicy: IfNotPresent
        name: cdi-operator
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 150Mi
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
